added header, react-icons & index.html bg
Sillen00/Netflix2.0 pull request #18
Opened 2023-12-05 18:44 UTC by leonbjorklund

2023-12-06 15:57 UTC, Edvindjulic requested changes
Konflikt i index.css efter merge av Ellens PR.

2023-12-07 09:14 UTC, Sillen00 commented
Märkte att när man söker i sökfältet och skrollar ner så hamnar vissa filmer utanför resultat div'en. Skulle det kunna gå att lösa?

2023-12-07 10:19 UTC, moamoa07 reviewed
Ser bra ut! Bara en liten sak att ändra i displayResult med typning

2023-12-07 10:19 UTC, moamoa07 commented on src/components/Header/DisplayResults.tsx
> +              year={movie.year.toString()}
Här är typen ändrat till number

2023-12-07 10:39 UTC, leonbjorklund commented on src/components/Header/DisplayResults.tsx
> +              year={movie.year.toString()}
oki

2023-12-07 10:42 UTC, moamoa07 approved these changes
Så bra!

2023-12-07 10:57 UTC, Edvindjulic approved these changes
index.css fixat - snyggt!

2023-12-07 10:57 UTC, merged